# Generated by Django 5.0.14 on 2026-09-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_update_profiles_fk'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='accounts.buyerprofile')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='listings.product')),
            ],
            options={
                'db_table': 'wishlist',
                'unique_together': {('buyer', 'product')},
            },
        ),
    ]
