# Generated by Django 5.0.14 on 2026-08-30 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_hi', models.CharField(default='', max_length=200)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_hi', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_image', models.ImageField(max_length=255, upload_to='products/raw/')),
                ('refined_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='products/refined/')),
                ('raw_audio', models.FileField(blank=True, max_length=255, null=True, upload_to='products/audio/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('flagged', 'Flagged')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(db_column='artisan_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.artisanprofile')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
