# Generated by Django 5.2.16 on 2026-09-04 07:09

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='raw_audio',
            field=models.FileField(blank=True, max_length=255, null=True, storage=listings.models.get_audio_storage, upload_to='products/audio/'),
        ),
    ]
