# Generated by Django 5.2.16 on 2026-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_add_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_paused',
            field=models.BooleanField(default=False),
        ),
    ]
