# Generated by Django 5.0.14 on 2026-08-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerprofile',
            options={'managed': False},
        ),
    ]
