# Generated by Django 5.2.16 on 2026-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_update_profiles_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/artisan/'),
        ),
    ]
