# Generated by Django 5.0.14 on 2026-08-30 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_update_profiles_fk'),
        ('cart', '0002_add_order_cost_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='buyer',
            field=models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.buyerprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='artisan',
            field=models.ForeignKey(db_column='artisan_id', on_delete=django.db.models.deletion.CASCADE, related_name='artisan_orders', to='accounts.artisanprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to='accounts.buyerprofile'),
        ),
    ]
