# Generated by Django 5.0.14 on 2026-08-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_update_profiles_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('payment_failed', 'Payment Failed'), ('payment_received', 'Payment Received'), ('awaiting_artisan_shipment', 'Awaiting Artisan Shipment'), ('in_transit_to_hub', 'In Transit to Hub'), ('at_hub_verification', 'At Hub Verification'), ('verification_failed', 'Verification Failed'), ('payout_released', 'Payout Released'), ('in_transit_to_buyer', 'In Transit to Buyer'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='payment_received', max_length=50),
        ),
    ]
