# Generated by Django 5.2.16 on 2026-09-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_update_profiles_fk'),
        ('cart', '0004_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='artisan',
            field=models.ForeignKey(blank=True, db_column='artisan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisan_orders', to='accounts.artisanprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, db_column='buyer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_orders', to='accounts.buyerprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(db_column='shipping_address_id', on_delete=django.db.models.deletion.PROTECT, to='cart.address'),
        ),
    ]
