# Generated by Django 5.0.14 on 2026-09-10 09:41

import django.db.models.deletion
import frames.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_update_profiles_fk'),
        ('listings', '0004_add_product_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(max_length=255, storage=frames.models.get_video_storage, upload_to='reels/videos/')),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, storage=frames.models.get_image_storage, upload_to='reels/thumbnails/')),
                ('caption', models.CharField(blank=True, max_length=300, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(db_column='artisan_id', on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='accounts.artisanprofile')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='listings.product')),
            ],
            options={
                'db_table': 'reels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(db_column='reel_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='frames.reel')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reel_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reel_likes',
                'ordering': ['-created_at'],
                'unique_together': {('reel', 'user')},
            },
        ),
    ]
